version: 0.2

phases:
  install:
    commands:
      - npm install
      - git init
      - git add --all
      - git commit -m "$1"
      - git push 
      - echo 'ls -l'
  build:
    commands:
      - npm test
artifacts:
  files:
    - '**/*'
